### PR TITLE
Add endpoints /acl and /manageACL for groupfolders

### PR DESCRIPTION
**Pull request by fangebee**
- [x] test giving advanced ACL to a simple user 
- [x] test giving advanced ACL to a group
- [x] test revoking advanced ACL to a simple user 
- [x] test revoking advanced ACL to a group
- [x] test enabling/disabling advanced ACL

### CODE REVIEW

**Comment by fangebee** [comment]
Hi @luffah I think this PR is ready for merging. Please can you review it?

**Comment by luffah** [comment]
Changes are accepted and are in :
https://github.com/luffah/nextcloud-API/commit/1a1d16030aa6a0485bf67aa04b734e042df5015b

**Comment by luffah** [comment]
Thank you very much for you work.

**Comment by luffah** [comment]
Your changes are in the new packaged version.

https://pypi.org/project/nextcloud-api-wrapper/#description

v0.2.2

**Comment by luffah** [comment]
Note : a little bug to fix on v0.2.2.
It will be re-included in pypi after the fix.

**Pull request closed without merging**
